### ISSUE TITLE
[refactor] 유저 데이터 react query로 가져오기 , 마이페이지 API 연동

### ISSUE THREAD

**Issue by Hj1218** [TUK-DP/frontend-v2#110]
### 리팩토링 할 부분
- 일기 조회 시 null이거나 undefined면 로그인으로 가도록

**Comment by Leewonchan14** [comment]
useGetUserId() 를 만들어서 전역 상태의 userId가 널이거나 undefined면 로그인 페이지로 전환
- [ ] 7/31 추가
  - useFetchDiary 와 useFetchDiaryCheck에서 사용되는 userId를 useGetUserId 에서 가져오는 것으로 변경
  - https://github.com/TUK-DP/frontend-v2/issues/78 이 이슈에서 사용되는 userId도 하드코딩 되어있다면 변경합니다.
  
  ### 기대효과
  자연스럽게 일기에 접근하면 로그인페이지로 넘어가게 설정 가능함
