### ISSUE TITLE
[refactor] 다른 페이지 갔다와도 키워드 처음으로 안넘어가게 변경

### ISSUE THREAD

**Issue by Leewonchan14** [TUK-DP/frontend-v2#123]
### 리팩토링 할 부분
다른 페이지 갔다와도 키워드 처음으로 안넘어가게 변경

**Comment by heedong12** [comment]
ai 도움받기나 다른 사람 그림 보기 갔다가 돌아오면 처음 키워드로 초기화 되는 것 고치기
