### ISSUE TITLE
[refactor]Bottom Sheet 수정

### ISSUE THREAD

**Issue by heedong12** [TUK-DP/frontend-v2#137]
### 리팩토링 할 부분
- 캘린더에서 보라색화면 올라오는 위치 수정 (뒤로가기가 보이도록)

- 그림이 그려진 일기인 경우 보라색화면에 그림 그리러 가는 버튼 없애기 + 그림 그리러 가는 버튼 글씨, 사진 크기 키우기 
  https://github.com/TUK-DP/backend/issues/175 이슈가 진행된 뒤에 진행

- 보라색화면 그림도 그려볼까요? 멘트 수정하기 ex)그림이 없네요 그림도 그려볼까요?

**Comment by Leewonchan14** [comment]
<img height="600" alt="image" src="https://github.com/user-attachments/assets/59008d90-9afa-43fe-8e3b-1b34af37a00d"><img height="600" alt="image" src="https://github.com/user-attachments/assets/ba615ff4-351e-4272-b261-db5d3926fc9d">
