### ISSUE TITLE
[publishing] 일기페이지 수정

### ISSUE THREAD

**Issue by Hj1218** [TUK-DP/frontend-v2#142]
### 퍼블리싱 할 페이지
 - [ ] 일기가 있는 경우 일기 삭제버튼 추가 + 삭제 확인 모달
 - [ ] 일기 새로고침 시 오늘 날짜의 일기 내용 안보이는 오류 수정

**Comment by Leewonchan14** [comment]
![화면 기록 2024-08-10 오후 3 52 41](https://github.com/user-attachments/assets/aab855de-33d0-4e20-b9f1-6bab123672ce)
