### ISSUE TITLE
[refactor] 그림일기 상태 저장 및 ai 크게보기 수정

### ISSUE THREAD

**Issue by heedong12** [TUK-DP/frontend-v2#143]
### 리팩토링 할 부분
- 그리는 화면 페이지에서 페이지 이동 후 돌아오면 그림 남아있도록 수정
- AI 그림받아서 확인 시 크기 조절 (패드에서 너무 작음, 크게 보기가 크게 보기가 아님)

**Comment by Leewonchan14** [comment]
```javascript
// src/components/helpWithAi/chat/ImageBlock.jsx
preview={{
  mask: <span className={"text-xl font-bold"}>크게 보기</span>,
  toolbarRender: () => {},
  imageRender: (_, { image }) => (
    <img className={"scale-150"} src={image.url} alt="" />
  ),
}}
```
@heedong12 
위처럼 작성시 크게 보기 1.5배 됩니다

<a href="https://ant.design/components/image" target="_blank">Ant design Image 컴포넌트 공식문서</a>
