### ISSUE TITLE
[publishing]AI 그림 투명도 조절 페이지

### ISSUE THREAD

**Issue by heedong12** [TUK-DP/frontend-v2#48]
### 퍼블리싱 할 페이지
- AI 그림 투명도 조절 페이지
<img width="160" alt="image" src="https://github.com/user-attachments/assets/45b6444a-6a00-43d7-884f-ed2f6548ddb8">

참고할 PR
https://github.com/TUK-DP/frontend-v2/pull/26

**Comment by Leewonchan14** [comment]
https://github.com/TUK-DP/frontend-v2/pull/52 로 해결
