### ISSUE TITLE
[publishing] 지는 가위바위보 게임 가이드 페이지, 게임 페이지 퍼블리싱, api 연동까지 

### ISSUE THREAD

**Issue by heedong12** [TUK-DP/frontend-v2#69]
### 퍼블리싱 할 페이지
<img width="531" alt="image" src="https://github.com/user-attachments/assets/d86497f3-e8ed-4199-a40f-f2598642ff74">

**Comment by Leewonchan14** [comment]
추후 게임페이지 수정으로 패드 화면 보완해야함
