### ISSUE TITLE
[publishing] 지는 가위바위보 게임 가이드 페이지, 게임 페이지 퍼블리싱, api 연동까지

### ISSUE THREAD

**Issue by Leewonchan14** [TUK-DP/frontend-v2#75]
### 퍼블리싱 할 페이지
<img width="531" alt="image" src="https://github.com/user-attachments/assets/d86497f3-e8ed-4199-a40f-f2598642ff74">

**Comment by Leewonchan14** [comment]
api 연동까지 완료하기

**Comment by heedong12** [comment]
- https://github.com/TUK-DP/frontend-v2/issues/89 이슈와 중복
